"""event_registrations_and_capacity

Revision ID: 0cf40034179d
Revises: 0be6d520cc27
Create Date: 2026-07-23 15:41:46.276338
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# Identifiants de révision Alembic.
revision: str = '0cf40034179d'
down_revision: Union[str, None] = '0be6d520cc27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_capacities',
    sa.Column('wp_event_id', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('wp_event_id')
    )
    op.create_table('event_registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('wp_event_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('registered', 'waitlisted', 'cancelled', name='eventregistrationstatus', native_enum=False, length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'wp_event_id', name='uq_user_event')
    )
    with op.batch_alter_table('event_registrations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_registrations_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_registrations_wp_event_id'), ['wp_event_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_registrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_registrations_wp_event_id'))
        batch_op.drop_index(batch_op.f('ix_event_registrations_user_id'))

    op.drop_table('event_registrations')
    op.drop_table('event_capacities')
    # ### end Alembic commands ###
