"""ideas_votes_comments

Revision ID: 4d924b085fda
Revises: 0cf40034179d
Create Date: 2026-07-23 15:50:04.426294
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# Identifiants de révision Alembic.
revision: str = '4d924b085fda'
down_revision: Union[str, None] = '0cf40034179d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ideas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=True),
    sa.Column('is_anonymous', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('new', 'under_review', 'accepted', 'rejected', 'archived', name='ideastatus', native_enum=False, length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ideas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ideas_author_id'), ['author_id'], unique=False)

    op.create_table('idea_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idea_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['idea_id'], ['ideas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('idea_comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_idea_comments_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_idea_comments_idea_id'), ['idea_id'], unique=False)

    op.create_table('idea_votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idea_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['idea_id'], ['ideas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idea_id', 'user_id', name='uq_idea_vote')
    )
    with op.batch_alter_table('idea_votes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_idea_votes_idea_id'), ['idea_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_idea_votes_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('idea_votes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_idea_votes_user_id'))
        batch_op.drop_index(batch_op.f('ix_idea_votes_idea_id'))

    op.drop_table('idea_votes')
    with op.batch_alter_table('idea_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_idea_comments_idea_id'))
        batch_op.drop_index(batch_op.f('ix_idea_comments_author_id'))

    op.drop_table('idea_comments')
    with op.batch_alter_table('ideas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ideas_author_id'))

    op.drop_table('ideas')
    # ### end Alembic commands ###
