"""daily status dashboard cards app settings desk positions

Revision ID: 440c5f41be08
Revises: a66ce9384d02
Create Date: 2026-07-23 14:31:00.690187
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# Identifiants de révision Alembic.
revision: str = '440c5f41be08'
down_revision: Union[str, None] = 'a66ce9384d02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('dashboard_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('highlighted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('daily_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('coworking', 'teletravail', 'deplacement', 'conge', name='workstatus', native_enum=False, length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'day', name='uq_user_day_status')
    )
    with op.batch_alter_table('daily_status', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_status_day'), ['day'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_status_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('desks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pos_x', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('pos_y', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('desks', schema=None) as batch_op:
        batch_op.drop_column('pos_y')
        batch_op.drop_column('pos_x')

    with op.batch_alter_table('daily_status', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_status_user_id'))
        batch_op.drop_index(batch_op.f('ix_daily_status_day'))

    op.drop_table('daily_status')
    op.drop_table('dashboard_cards')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
